# Generated by Django 5.2.9 on 2026-01-20 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb_app', '0002_city_city_name_en_city_city_name_jp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='city_name_jp',
            new_name='city_name_ja',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='descriptions_jp',
            new_name='descriptions_ja',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='title_jp',
            new_name='title_ja',
        ),
        migrations.RenameField(
            model_name='rules',
            old_name='rules_name_jp',
            new_name='rules_name_ja',
        ),
    ]
